### ISSUE TITLE
Got Error While Initialization Amplitude Experiment in Production

### ISSUE THREAD

**Issue by adityaputra11** [amplitude/experiment-react-native-client#19]
i got issue when using amplitude init in production currently i am using 

```
"@amplitude/react-native": "2.10.0",
"@amplitude/experiment-react-native-client": "^0.7.0",
 "react-native": "0.70.6",
```

![Screenshot 2023-02-02 at 14 20 53](https://user-images.githubusercontent.com/24503826/216258125-5c0d2eaa-c5f1-452c-914f-8f32bd230a85.png)

**Comment by bgiori** [comment]
Hi @adityaputra11, sorry you're running into this issue. Unfortunately I'm not sure exactly which line is causing this issue. 

Is it possible to reproduce locally in order to understand exactly which line and function are throwing due to the null pointer?

Based on the formatting, this is coming from Android when the javascript wrapper is calling into the native android library.

**Comment by adityaputra11** [comment]
yes, issue comes from native android library, it already solve this issue is not affected app after deep investigation
thanks @bgiori for concern
